export { default as CalendarPage } from './CalendarPage';
export { default as CreditCard } from './CreditCard';
export { default as EditorPage } from './EditorPage';
export { default as HlsPage } from './HlsPage';
export { default as HomePage } from './HomePage';
export { default as LoginPage } from './LoginPage';
export { default as NotFoundPage } from './NotFoundPage';
export { default as QRCodePage } from './QRCodePage';
export { default as LanguagePage } from './LanguagePage';
